Create 01-dotenv.nvim.md
phaazon/this-week-in-neovim-contents pull request #103
Opened 2022-12-06 00:01 UTC by ellisonleao

2022-12-11 20:01 UTC, phaazon requested changes

2022-12-11 20:01 UTC, phaazon commented on contents/2022/Dec/12/03-new-plugins/01-dotenv.nvim.md
> +    <a href="#new-dotenv">
The anchor is not the same.

2022-12-11 20:10 UTC, ellisonleao commented on contents/2022/Dec/12/03-new-plugins/01-dotenv.nvim.md
> +    <a href="#new-dotenv">
fixed

2022-12-11 23:11 UTC, phaazon approved these changes

2022-12-11 23:11 UTC, merged

2022-12-12 10:35 UTC, phaazon commented
Also, I hadn’t noticed but you put the file in the wrong folder. Do not create directories in your PRs please.