feat: Add neogen 2.11 core update
phaazon/this-week-in-neovim-contents pull request #118
Opened 2023-01-03 02:34 UTC by danymat

Hello, I'm adding updates for Neogen for this week update following https://github.com/danymat/neogen/pull/116.

2023-01-04 18:55 UTC, Amar1729 commented
Shouldn't these files be added to `4-updates` (for plugins) rather than `0-core-updates` (for updates to neovim core)?

2023-01-04 19:59 UTC, danymat commented
Oh well maybe, I will fix that

2023-01-05 15:37 UTC, phaazon commented
Thanks! Yes please follow the templates, that will help me when I finalize the last merge.

2023-01-06 10:54 UTC, danymat commented
Done !

2023-01-06 12:26 UTC, phaazon requested changes
Please follow `4-updates/1-example.md` for the formatting.

2023-01-08 22:40 UTC, phaazon approved these changes

2023-01-08 22:40 UTC, phaazon commented on contents/2023/Jan/09/4-updates/2-neogen.md
> +> Neogen is a better annotation generator. Supports multiple languages and annotation conventions.
I’m going to merge this but just for the future, please refrain from using words like _better_, especially without comparing to anything else and explaining why it would be better. I think it’s okay but it can be annoying / disrespectful for some people.

2023-01-08 22:40 UTC, merged