Create [2-guides] migrate from Packer to Lazy
phaazon/this-week-in-neovim-contents pull request #138
Opened 2023-01-11 04:05 UTC by al-ce

Did not embed the video, the thumbnail is an external link to YouTube

2023-01-13 16:17 UTC, phaazon requested changes
Thank you! May you squash all your commits, please?

2023-01-13 16:17 UTC, phaazon commented on contents/2023/Jan/16/2-guides/1-migrate-from-packer-to-lazy.md
> +
You can remove the newline here.

2023-01-15 04:40 UTC, elijahmanor commented
Yay, thanks for this! I was dropping by to see if I should contribute this, but see that you all have it covered! @al-ce and @phaazon thank you both for your work!

2023-01-15 20:04 UTC, phaazon approved these changes
Thanks!

2023-01-15 20:04 UTC, merged