[new plugin] markdowny.nvim
phaazon/this-week-in-neovim-contents pull request #143
Opened 2023-01-13 11:24 UTC by antonk52

2023-01-13 22:32 UTC, phaazon commented
Please target the right branch. I’m changing the base branch.

2023-01-13 22:34 UTC, phaazon requested changes

2023-01-13 22:34 UTC, phaazon commented on contents/2023/Jan/16/3-new-plugins/1-markdowny.nvim.md
> +A new plugin by @antonk52 to add markdown like shortcuts similar to Reddit/Notion/Slack/Discord etc
Add a link to your GitHub page on `@antonk52`.

2023-01-13 22:34 UTC, phaazon commented on contents/2023/Jan/16/3-new-plugins/1-markdowny.nvim.md
> +A new plugin by @antonk52 to add markdown like shortcuts similar to Reddit/Notion/Slack/Discord etc
Also, please use _Markdown_ instead of _markdown_.

2023-01-13 22:34 UTC, phaazon commented on contents/2023/Jan/16/3-new-plugins/1-markdowny.nvim.md
> +A new plugin by @antonk52 to add markdown like shortcuts similar to Reddit/Notion/Slack/Discord etc
And dot at the end of the sentence.

2023-01-14 12:41 UTC, antonk52 commented on contents/2023/Jan/16/3-new-plugins/1-markdowny.nvim.md
> +A new plugin by @antonk52 to add markdown like shortcuts similar to Reddit/Notion/Slack/Discord etc
Thanks for the review! Fixed.

2023-01-15 20:06 UTC, merged