Describe fixed JSX highlighting in nvim-ts-rainbow
phaazon/this-week-in-neovim-contents pull request #19
Opened 2022-08-08 08:13 UTC by Gelio

I wanted to mention my latest contribution to [nvim-ts-rainbow](https://github.com/p00f/nvim-ts-rainbow) that fixes JSX props highlighting - [an issue](https://github.com/p00f/nvim-ts-rainbow/issues/118) that annoyed me for quite some time.

2022-08-08 12:46 UTC, phaazon requested changes
Sure thing! However, can you please have a look at the previous days and follow the same formatting with headers, anchors, etc.? Thanks.

2022-08-08 13:01 UTC, Gelio commented
Alright, I updated the heading to use HTML elements instead of a Markdown heading. This is the only difference I found. Let me know if there are more things you'd like fixed and I failed to spot the differences

2022-08-09 14:35 UTC, phaazon approved these changes
All good, thank you!

2022-08-09 14:35 UTC, merged

2022-08-09 20:37 UTC, phaazon commented
You’re very welcome @Gelio