More updates
phaazon/this-week-in-neovim-contents pull request #209
Opened 2023-03-02 11:44 UTC by WhiteBlackGoose

2023-03-03 22:49 UTC, phaazon requested changes

2023-03-03 22:49 UTC, phaazon commented on contents/2023/Apr/06/2-guides/1-example.md
> -<h3 id="guide-your-content">
Please do not remove that file as it will be useful for others. You can use the `1-` number, it doesn’t matter as I resort everything before merging everything to master.

2023-03-03 22:49 UTC, phaazon commented on contents/2023/Apr/06/3-new-plugins/1-example.md
> -<h3 id="new-your-plugin.nvim">
Ditto.

2023-03-04 02:51 UTC, WhiteBlackGoose commented on contents/2023/Apr/06/2-guides/1-example.md
> -<h3 id="guide-your-content">
Done. FWIW, I'm not sure if preconfig belongs to guides... but idk where it fits

2023-03-05 23:24 UTC, phaazon commented on contents/2023/Apr/06/2-guides/1-example.md
> -<h3 id="guide-your-content">
I think it’s okay.

2023-03-05 23:25 UTC, phaazon approved these changes

2023-03-05 23:25 UTC, merged