Add colortils.nvim
phaazon/this-week-in-neovim-contents pull request #36
Opened 2022-08-29 16:15 UTC by max397574

not sure if everything is correct like this
I just copied things from a different pr and modified what I thought had to be modified

2022-08-30 08:18 UTC, max397574 commented
@phaazon ?

2022-08-31 12:32 UTC, phaazon requested changes

2022-08-31 12:32 UTC, phaazon commented on contents/2022/Sep/05.md
> +A neovim plugin for working with colors.
I think the text should be a bit more description than that, if possible. Thank you in advance.

2022-08-31 12:32 UTC, phaazon commented on contents/2022/Sep/05.md
> +- [Reddit](https://www.reddit.com/r/neovim/comments/x0s3ku/colortilsnvim_work_with_colors_in_neovim/)
May you swap those lines? Everywhere else the reddit link comes first.

2022-08-31 16:49 UTC, max397574 commented on contents/2022/Sep/05.md
> +A neovim plugin for working with colors.
better now @phaazon ?

2022-09-01 14:33 UTC, phaazon approved these changes

2022-09-01 14:33 UTC, phaazon commented on contents/2022/Sep/05.md
> +h3 id="new-colortils.nvim">
The tag is messed up but I will fix that.

2022-09-01 14:33 UTC, merged