Add jc.nvim
phaazon/this-week-in-neovim-contents pull request #61
Opened 2022-10-10 13:38 UTC by zjp-CN

2022-10-11 17:54 UTC, phaazon requested changes
A couple of nits but overall okay, thank you!

2022-10-11 17:54 UTC, phaazon commented on contents/2022/Oct/10.md
> +jc.nvim – successor of [vim-javacomplete2](https://github.com/artur-shaik/vim-javacomplete2)
```suggestion
`jc.nvim` – successor of [vim-javacomplete2](https://github.com/artur-shaik/vim-javacomplete2)
```

2022-10-11 17:54 UTC, phaazon commented on contents/2022/Oct/10.md
> +which use neovim's built-in LSP client and [Eclipse JDT Language Server](https://github.com/eclipse/eclipse.jdt.ls).
```suggestion
which uses Neovim's built-in LSP client and [Eclipse JDT Language Server](https://github.com/eclipse/eclipse.jdt.ls).
```

2022-10-11 17:54 UTC, phaazon commented on contents/2022/Oct/10.md
> +Main goal of this project is to migrate functionallty of jc2.
```suggestion
Main goal of this project is to migrate all the functionallties of jc2 to Neovim.
```

2022-10-11 17:54 UTC, phaazon commented on contents/2022/Oct/10.md
> +In addition to autocompletion it can:
```suggestion
In addition to autocompletion, it can:
```

2022-10-11 17:54 UTC, phaazon commented on contents/2022/Oct/10.md
> +It's written by [@artur-shaik](https://github.com/artur-shaik) and you read his [blog post](https://shaik.link/posts/javacomplete-to-jc.nvim/) about it.
```suggestion
It's written by [@artur-shaik](https://github.com/artur-shaik) and you can read his [blog post](https://shaik.link/posts/javacomplete-to-jc.nvim/) about it.
```

2022-10-12 08:27 UTC, zjp-CN commented
Seems I should submit this PR to [2022-Oct-17](https://github.com/phaazon/this-week-in-neovim-contents/tree/2022-Oct-17) branch? I realized the branch name indicates the deadline on merge...

2022-10-12 12:21 UTC, phaazon commented
> Seems I should submit this PR to [2022-Oct-17](https://github.com/phaazon/this-week-in-neovim-contents/tree/2022-Oct-17) branch? I realized the branch name indicates the deadline on merge...

Yes, please change the base branch. You shouldn’t have any issues.

2022-10-12 12:28 UTC, closed without merging